#pragma once
#include "CoreMinimal.h"
#include "EYActivityType.generated.h"

UENUM(BlueprintType)
enum class EYActivityType : uint8 {
    None,
    Area,
    AlienForge,
    AI_Guardians,
    AI_Spawning,
    BigDrill,
    BossHunt,
    DataRetrieval,
    Delivery,
    Deposit,
    Dungeon,
    Escape,
    Flora,
    Flora_WaterPlant,
    Flora_IvyPlant,
    Flora_DesertPlant,
    Flora_BonePlant,
    Hunt,
    Mineral_AlienCrystals,
    Mineral_BasicOres,
    Mineral_HeavyMetals,
    Mineral_Radioactive,
    Mineral_Veltecite,
    Mineral_GlowingCrystal,
    Mineral_AlienIron,
    MonsterNest,
    NoiseTrap_Birds,
    OilPump_Tier0,
    OilPump_Tier1,
    OilPump_Tier2,
    OilPump_Tier3,
    OilPump_Tier4,
    PowerUp,
    StormSurge,
    Tracking,
    Train,
    Meteor,
    Uplink,
    LootContainers,
    LootPoints,
    All,
    MAX,
};

