#pragma once
#include "CoreMinimal.h"
#include "EYInputActionName.generated.h"

UENUM(BlueprintType)
enum class EYInputActionName : uint8 {
    Turn,
    LookUp,
    SwitchWeapon1,
    SwitchWeapon2,
    SwitchWeapon3,
    SwitchWeapon4,
    SwitchWeapon5,
    SwitchWeapon6,
    SwitchWeapon7,
    SwitchWeapon8,
    SwitchWeapon9,
    NextWeapon,
    PrevWeapon,
    Fire,
    Targeting,
    Reload,
    ActivateAbility1,
    ActivateAbility2,
    Interact,
    Team,
    MatchInventory,
    ToggleMap,
    Chat,
    SpectateNext,
    SpectatePrev,
    SpectateZoomIn,
    SpectateZoomOut,
    SpectateCamera,
    Debug_ToggleMasterDebugWidget,
    Social,
    Social_GoThere,
    Social_Enemies,
    DamageRecap,
    Challenge,
    ToggleLobbyHUD,
    Emote,
    Banner,
    QuickBuy1,
    QuickBuy2,
    QuickBuy3,
    QuickBuy4,
    Debug_BugIt,
    PushToTalk,
    ToggleStationMap,
    QuickMenu,
    ActivateConsumable,
    ToolWheel,
    ConsumableWheel,
    Melee,
    HideHud,
    OpenAttachmentScreen,
    AnyKey,
    LookUpController,
    TurnController,
    UiNextSortingMethod,
    MuteIncomingVOIP,
    None,
};

