#pragma once
#include "CoreMinimal.h"
#include "EYPlayerStateBlueprint.generated.h"

UENUM(BlueprintType)
enum class EYPlayerStateBlueprint : uint8 {
    None,
    Crouching,
    Sprinting,
    Targeting,
    Reloading,
    Firing,
    WeaponSwitch,
    SpiningUp,
    Interacting,
    Death,
    ReloadAnimation,
    NOTUSED4,
    Melee,
    Emote,
    Inventory,
    Slide,
    NOTUSED5,
    NOTUSED6,
    Use,
    NOTUSED7,
    NOTUSED8,
    DBNO,
    Revive,
    ReloadAmmo,
    NOTUSED9,
    HardLanding,
    Prototype,
    Vehicle,
    VehicleLeaving,
    Banner,
    NOTUSED3,
    ChargingAttack,
    Ability,
    NOTUSED1,
    Carrying,
    Climbing,
    Prone,
    NOTUSED10,
    NOTUSED2,
    MeleeHeavy,
    MAX,
};

