#pragma once
#include "CoreMinimal.h"
#include "EYStartItemCraftingResultStatus.h"
#include "YOnItemCraftingStartedResponseReceivedBackendSignatureDelegate.generated.h"

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FYOnItemCraftingStartedResponseReceivedBackendSignature, const EYStartItemCraftingResultStatus, startItemCraftingStatus);

