#pragma once
#include "CoreMinimal.h"
#include "EYPurchaseWeaponShopItemStatus.h"
#include "YOnWeaponShopItemPurchaseResponseReceivedBackendOldSignatureDelegate.generated.h"

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FYOnWeaponShopItemPurchaseResponseReceivedBackendOldSignature, EYPurchaseWeaponShopItemStatus, purchaseWeaponShopItemStatus);

