#pragma once
#include "CoreMinimal.h"
#include "EYClaimContractRewardsStatus.generated.h"

UENUM(BlueprintType)
enum class EYClaimContractRewardsStatus : uint8 {
    UNKNOWN_ERROR,
    CLAIMING_ONE_TIME_CONTRACT,
    FAILED_FACTION_PARSING,
    FAILED_GETTING_FACTION_PROGRESSION,
    FAILED_GETTING_STATIC_DATA,
    FAILED_GIVING_REWARDS,
    FAILED_REMOVAL_ACTIVE_CONTRACT,
    FAILED_SETTING_DATA,
    NO_ACTIVE_CONTRACT,
    NO_CONTRACTS_BOARDS_DATA_FOUND,
    NO_FACTION_DATA,
    STASH_FULL,
    STASH_LIMIT_NOT_FOUND,
    WRONG_CONTRACT_ID,
    WRONG_FACTION_ID,
    WRONG_FACTION_REP,
    PROGRESS_MISSING,
    FAILED_ACQUIRING_REDIS_LOCK,
    OK,
    MAX,
};

